feature : all changes releated to "Pasarela de pagos"
paolorossig/edu-tech pull request #2
Opened 2022-01-12 00:49 UTC by cesar4rroyo

2022-01-12 01:03 UTC, cesar4rroyo commented
-CardPay, CardSecurity, CreditCard, DetailPay and ModalPay Components were added to the main component (Pasarela).

2022-01-12 22:10 UTC, carosalazar28 requested changes
Excelente trabajo!! un par de comments que te deje

2022-01-12 22:10 UTC, carosalazar28 commented on src/pages/checkout/Pasarela.jsx
> +  const [showModal, setShowModal] = React.useState(false)
Puedes mejorar la sintaxis importando useState de React.

```
import { useState } from 'react'

const [showModal, setShowModal] = useState(false)
```

2022-01-12 22:10 UTC, carosalazar28 commented on src/pages/checkout/Pasarela.jsx
> +                <CardPay element={curso} key={index} />
Solo como recomendación las buenas practicas dicen que utilizar el index como el key de un componente no es recomendable porqué es un prop susceptible a cambio.

2022-01-12 22:10 UTC, carosalazar28 commented on src/pages/checkout/components/CardPay.jsx
> +    nivel
Trata de ser consistente con el lenguaje de las variables

2022-01-12 22:10 UTC, carosalazar28 commented on src/pages/checkout/components/CardSecurity.jsx
> +    <>
Estos fragment creó que sobran porque ya tienes un div que encapsula todo el código.

2022-01-12 22:10 UTC, carosalazar28 commented on src/pages/checkout/components/CreditCards.jsx
> +        )}
Esto se puede mejorar, el propio elemento de input tiene un prop con el que identifica cual es el que está seleccionado.

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/radio

Revisa la documentación y agrégale los props de `name` y `id`

2022-01-20 00:42 UTC, cesar4rroyo commented
For revision 🤓

2022-01-20 15:50 UTC, carosalazar28 approved these changes

2022-01-20 16:16 UTC, paolorossig approved these changes

2022-01-20 16:18 UTC, merged